from django.urls import path

from trading.views_admin import (
    AdminForceAssignmentView,
    AdminIngestedPostDetailView,
    AdminIngestedPostListView,
    AdminDecisionListView,
    AdminPerformanceByStrategyView,
    AdminPerformanceByTierView,
    AdminPlatformStatsView,
    AdminPositionListView,
    AdminResearchEventDetailView,
    AdminResearchEventListView,
    AdminResearchParseView,
    AdminSignalDecisionListView,
    AdminSignalDetailView,
    AdminSignalListCreateView,
    AdminStrategyDetailView,
    AdminStrategyEventListView,
    AdminStrategyListCreateView,
    AdminStrategyLookbackView,
    AdminStrategyPostListView,
    AdminStrategyResearchIngestView,
    AdminStrategyResearchPollView,
    AdminStrategySignalListView,
    AdminStrategyTypeListView,
    AdminTierDetailView,
    AdminTierListView,
    AdminTierUsageView,
    AdminTradeDetailView,
    AdminTradeListView,
    AdminUserDetailView,
    AdminUserGroupDetailView,
    AdminUserGroupListCreateView,
    AdminUserListView,
    AdminWatchedCompanyDetailView,
    AdminWatchedCompanyListCreateView,
    AdminXParseView,
    AdminXSourceDetailView,
    AdminXSourceIngestView,
    AdminXSourceListCreateView,
    AdminXSourcePollView,
)
from trading.views_user import (
    AssignmentView,
    BrokerAccountDetailView,
    BrokerAccountListView,
    BrokerAgentToolsView,
    BrokerConnectionListCreateView,
    BrokerDisconnectView,
    BrokerSelectAccountView,
    DecisionDetailView,
    DecisionListView,
    InvestmentTierListView,
    NotificationListView,
    NotificationReadView,
    PerformanceView,
    PositionListView,
    RobinhoodOAuthCallbackView,
    RobinhoodOAuthCompleteView,
    RobinhoodOAuthStartView,
    StrategyListView,
    StrategySignalListView,
    TradeDetailView,
    TradeListView,
)

urlpatterns = [
    path("strategies/", StrategyListView.as_view(), name="strategy-list"),
    path(
        "strategies/<int:pk>/signals/",
        StrategySignalListView.as_view(),
        name="strategy-signals",
    ),
    path("investment-tiers/", InvestmentTierListView.as_view(), name="tier-list"),
    path("assignment/", AssignmentView.as_view(), name="assignment"),
    path("broker-connections/", BrokerConnectionListCreateView.as_view(), name="broker-list"),
    path(
        "broker-connections/robinhood/oauth/start/",
        RobinhoodOAuthStartView.as_view(),
        name="robinhood-oauth-start",
    ),
    path(
        "broker-connections/robinhood/oauth/complete/",
        RobinhoodOAuthCompleteView.as_view(),
        name="robinhood-oauth-complete",
    ),
    path(
        "broker-connections/robinhood/oauth/callback/",
        RobinhoodOAuthCallbackView.as_view(),
        name="robinhood-oauth-callback",
    ),
    path(
        "broker-connections/<int:pk>/accounts/<str:account_number>/",
        BrokerAccountDetailView.as_view(),
        name="broker-account-detail",
    ),
    path(
        "broker-connections/<int:pk>/accounts/",
        BrokerAccountListView.as_view(),
        name="broker-accounts",
    ),
    path(
        "broker-connections/<int:pk>/select-account/",
        BrokerSelectAccountView.as_view(),
        name="broker-select-account",
    ),
    path(
        "broker-connections/<int:pk>/agent-tools/",
        BrokerAgentToolsView.as_view(),
        name="broker-agent-tools",
    ),
    path(
        "broker-connections/<int:pk>/disconnect/",
        BrokerDisconnectView.as_view(),
        name="broker-disconnect",
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("trades/", TradeListView.as_view(), name="trade-list"),
    path("trades/<int:pk>/", TradeDetailView.as_view(), name="trade-detail"),
    path("decisions/", DecisionListView.as_view(), name="decision-list"),
    path("decisions/<int:pk>/", DecisionDetailView.as_view(), name="decision-detail"),
    path("performance/", PerformanceView.as_view(), name="performance"),
    path("notifications/", NotificationListView.as_view(), name="notification-list"),
    path(
        "notifications/<int:pk>/read/",
        NotificationReadView.as_view(),
        name="notification-read",
    ),
    path("admin/strategies/", AdminStrategyListCreateView.as_view(), name="admin-strategy-list"),
    path(
        "admin/strategies/<int:pk>/",
        AdminStrategyDetailView.as_view(),
        name="admin-strategy-detail",
    ),
    path(
        "admin/strategies/<int:pk>/posts/",
        AdminStrategyPostListView.as_view(),
        name="admin-strategy-posts",
    ),
    path(
        "admin/strategies/<int:pk>/signals/",
        AdminStrategySignalListView.as_view(),
        name="admin-strategy-signals",
    ),
    path(
        "admin/strategies/<int:pk>/lookback/",
        AdminStrategyLookbackView.as_view(),
        name="admin-strategy-lookback",
    ),
    path(
        "admin/strategies/<int:pk>/events/",
        AdminStrategyEventListView.as_view(),
        name="admin-strategy-events",
    ),
    path(
        "admin/strategies/<int:pk>/research-poll/",
        AdminStrategyResearchPollView.as_view(),
        name="admin-strategy-research-poll",
    ),
    path(
        "admin/strategies/<int:pk>/research-ingest/",
        AdminStrategyResearchIngestView.as_view(),
        name="admin-strategy-research-ingest",
    ),
    path(
        "admin/strategy-types/",
        AdminStrategyTypeListView.as_view(),
        name="admin-strategy-types",
    ),
    path("admin/investment-tiers/", AdminTierListView.as_view(), name="admin-tier-list"),
    path(
        "admin/investment-tiers/<int:pk>/",
        AdminTierDetailView.as_view(),
        name="admin-tier-detail",
    ),
    path("admin/tier-usage/", AdminTierUsageView.as_view(), name="admin-tier-usage"),
    path("admin/platform-stats/", AdminPlatformStatsView.as_view(), name="admin-platform-stats"),
    path(
        "admin/performance/by-tier/",
        AdminPerformanceByTierView.as_view(),
        name="admin-performance-by-tier",
    ),
    path(
        "admin/performance/by-strategy/",
        AdminPerformanceByStrategyView.as_view(),
        name="admin-performance-by-strategy",
    ),
    path(
        "admin/user-groups/",
        AdminUserGroupListCreateView.as_view(),
        name="admin-user-group-list",
    ),
    path(
        "admin/user-groups/<int:pk>/",
        AdminUserGroupDetailView.as_view(),
        name="admin-user-group-detail",
    ),
    path("admin/users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path(
        "admin/users/assignment/",
        AdminForceAssignmentView.as_view(),
        name="admin-force-assignment",
    ),
    path("admin/signals/", AdminSignalListCreateView.as_view(), name="admin-signal-list"),
    path(
        "admin/signals/<int:pk>/",
        AdminSignalDetailView.as_view(),
        name="admin-signal-detail",
    ),
    path(
        "admin/signal-decisions/",
        AdminSignalDecisionListView.as_view(),
        name="admin-signal-decisions",
    ),
    path("admin/decisions/", AdminDecisionListView.as_view(), name="admin-decisions"),
    path("admin/trades/", AdminTradeListView.as_view(), name="admin-trade-list"),
    path("admin/trades/<int:pk>/", AdminTradeDetailView.as_view(), name="admin-trade-detail"),
    path("admin/positions/", AdminPositionListView.as_view(), name="admin-position-list"),
    path("admin/x-sources/", AdminXSourceListCreateView.as_view(), name="admin-x-source-list"),
    path(
        "admin/x-sources/<int:pk>/",
        AdminXSourceDetailView.as_view(),
        name="admin-x-source-detail",
    ),
    path(
        "admin/x-sources/<int:pk>/poll/",
        AdminXSourcePollView.as_view(),
        name="admin-x-source-poll",
    ),
    path(
        "admin/x-sources/<int:pk>/ingest/",
        AdminXSourceIngestView.as_view(),
        name="admin-x-source-ingest",
    ),
    path("admin/x-parse/", AdminXParseView.as_view(), name="admin-x-parse"),
    path("admin/x-posts/", AdminIngestedPostListView.as_view(), name="admin-x-post-list"),
    path(
        "admin/x-posts/<int:pk>/",
        AdminIngestedPostDetailView.as_view(),
        name="admin-x-post-detail",
    ),
    path(
        "admin/watched-companies/",
        AdminWatchedCompanyListCreateView.as_view(),
        name="admin-watched-company-list",
    ),
    path(
        "admin/watched-companies/<int:pk>/",
        AdminWatchedCompanyDetailView.as_view(),
        name="admin-watched-company-detail",
    ),
    path("admin/research-parse/", AdminResearchParseView.as_view(), name="admin-research-parse"),
    path(
        "admin/research-events/",
        AdminResearchEventListView.as_view(),
        name="admin-research-event-list",
    ),
    path(
        "admin/research-events/<int:pk>/",
        AdminResearchEventDetailView.as_view(),
        name="admin-research-event-detail",
    ),
]
