# Generated by Django 5.2.12 on 2026-08-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('no_trade', 'No trade'), ('skipped', 'Skipped'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('parsed_trades', models.JSONField(default=list)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='XAccountSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='X username without @.', max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('x_user_id', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('lookback_hours', models.PositiveSmallIntegerField(default=48, help_text='Ignore tweets older than this on ingest.')),
                ('last_tweet_id', models.CharField(blank=True, max_length=32)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['handle'],
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='ingested_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='trading.ingestedpost'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(condition=models.Q(('ingested_post__isnull', False)), fields=('ingested_post', 'ticker', 'option_type', 'strike', 'expiration'), name='one_signal_per_post_contract'),
        ),
        migrations.AddField(
            model_name='xaccountsource',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='x_sources', to='trading.strategy'),
        ),
        migrations.AddField(
            model_name='ingestedpost',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='trading.xaccountsource'),
        ),
        migrations.AddConstraint(
            model_name='ingestedpost',
            constraint=models.UniqueConstraint(fields=('source', 'tweet_id'), name='unique_tweet_per_x_source'),
        ),
    ]
