# Generated by Django 5.2.12 on 2026-08-15 22:40

import django.core.validators
from django.db import migrations, models


def rename_copy_trade_strategy(apps, schema_editor):
    Strategy = apps.get_model("trading", "Strategy")
    Strategy.objects.filter(slug="copy-trade", name="Copy Trade").update(
        name="Copy Trade from X"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_x_account_watcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="xaccountsource",
            name="poll_interval_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How often to pull new posts from X, in seconds.",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(86400),
                ],
            ),
        ),
        migrations.RunPython(rename_copy_trade_strategy, migrations.RunPython.noop),
    ]
