# Generated by Django 5.2.12 on 2026-08-15 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_x_poll_interval_and_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategy',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], db_index=True, default='public', help_text='public: every user can pick it. restricted: only allowed_users and allowed_groups.', max_length=16),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='trading_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='strategies', to='trading.usergroup'),
        ),
    ]
