# Generated by Django 5.2.12 on 2026-08-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_copy_trade_signal_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enter', 'Enter'), ('skip', 'Skip'), ('take_profit', 'Take profit'), ('stop_loss', 'Stop loss'), ('time_exit', 'Time exit'), ('force_exit', 'Force exit'), ('expiration_exit', 'Expiration exit'), ('daily_pause', 'Daily loss pause')], db_index=True, max_length=32)),
                ('outcome', models.CharField(choices=[('acted', 'Acted'), ('passed', 'Passed')], db_index=True, max_length=16)),
                ('reason_code', models.CharField(blank=True, choices=[('tier_size', 'Sized by investment tier'), ('no_broker', 'No brokerage connection'), ('paused', 'Daily loss pause'), ('daily_loss_limit', 'Daily loss limit'), ('max_open_positions', 'Max open positions'), ('slippage', 'Entry slippage'), ('size_zero', 'Position size rounded to zero'), ('broker_error', 'Broker error'), ('unfilled', 'Order did not fill'), ('wrong_account', 'Assigned to a different brokerage account'), ('take_profit', 'Take-profit rule'), ('stop_loss', 'Hard stop'), ('time_exit', 'Max hold'), ('force_exit', 'Force exit'), ('expiration_exit', 'Expiration force exit'), ('daily_pause', 'Daily loss pause')], max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=16)),
                ('option_type', models.CharField(blank=True, max_length=4)),
                ('strike', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('broker_account_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='trading.investmenttier')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='trading.signal')),
                ('signal_decision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='trading.signaldecision')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='trading.strategy')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='trading.trade')),
                ('trade_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='trading.tradeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trading.decision'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['user', '-created_at'], name='trading_dec_user_id_ef0163_idx'),
        ),
    ]
